version: "3.9"

services:
  neo4j:
    image: neo4j:5.15
    container_name: rare-neo4j-standalone
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
      - ./import:/import
      - ./guides:/guides
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["graph-data-science", "apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_whitelist=gds.*,apoc.*
